# Generated by Django 3.0.2 on 2022-01-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('DataId', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('ChamberTemp', models.CharField(max_length=500)),
                ('AmbientTemp', models.CharField(max_length=500)),
                ('ChamberHum', models.CharField(max_length=500)),
                ('ChamberLight', models.CharField(max_length=500)),
                ('ChamberCO2', models.CharField(max_length=500)),
                ('ChamberWater', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('PhotoId', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('Position', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
