# Generated by Django 3.0.2 on 2022-01-24 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChamberApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='data',
            name='Time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='photo',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='photo',
            name='Time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
